baseurl = "https://sriram.netlify.com/"
languageCode = "en-us"
title = "Blog"
theme = "blackburn"
author = "Sriram Sambasivam"
copyright = "&copy; 2018. All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  # subtitle = "Personal blog"
  brand = "Sriram<br>Sambasivam"
  googleAnalytics = ""
  disqus = ""
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
    
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"
    
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
    
  # [[menu.main]]
  #  name = "Topics"
  #  pre = "<i class='fa fa-folder fa-fw'></i>"
  #  weight = 3
  #  identifier = "topic"
  #  url = "/topics/"
    
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
    
[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  linkedin = "srirampsambasivam"
  github   = "SriramNY"
  twitter  = "SriramSNY"